### ISSUE TITLE
It often does not translate individual words.

### ISSUE THREAD

**Issue by FiveFme** [sienori/simple-translate#508] opened 2023-09-15 00:34 UTC
Target/Second language doesn't matter. 
It was even in version 2.8.1.

Didn't used to be the case.

FireFox 117.0.1 (64-bit).

**Comment by tarasverq** [comment] 2023-09-16 07:09
Same here.

TypeError: e.terms is undefined [content.js:2:172597] (moz-extension://4e166bea-5c19-4863-9693-a6d70c4f438a/content/content.js)

But okay with 2+ words
![image](https://github.com/sienori/simple-translate/assets/8226275/390b3d67-3e7b-4c8d-8485-14fd285f6236)

**Comment by gashihiko** [comment] 2023-09-16 08:32
I have the same problem with my Firefox for Arch Linux 117.0.1 (64-bit).
Console shows e.terms is undefined.

**Comment by gashihiko** [comment] 2023-09-16 08:54
Seems like this problem often happen with English words. Even if I set the default language to Russian and secondary to Italian, single English words can't be translated very often. But some words like "Firefox" can be translated.

And the problem doesn't happen when I set the default language to English. English to English translation shows a result for every single English word.

**Comment by NineMeowICT** [comment] 2023-09-16 09:01
Same here.

**Comment by gashihiko** [comment] 2023-09-16 09:09
Oh, it might be a duplicate of #505 and #506, and it has been solved by #507.

**Comment by amordo** [comment] 2023-09-16 10:25
Same here, chrome. Earlier had no such problem, bug with update?

**Comment by francesco-cadei** [comment] 2023-09-17 06:17
Same:

- SimpleTranslate 2.8.2
- Firefox 102.13.0esr
- Debian 12

**Comment by llleeexxxoooppp** [comment] 2023-09-17 09:00
Same problem. Single words don't translating, but with chunk of text it works.
That's went after last update (simple translate) as i assume.
Languages: English and Russian | Firefox 117.0 (64-bit) | Mozilla Firefox for Ubuntu canonical-1.0 | KDE Neon

**Comment by OnurDnz** [comment] 2023-09-18 07:27
Same problem 

- 117.0.1 (64-bit)
- MacOs Venture Version 13.5
- Simple Translate 2.8.2

**Comment by SilentPrayeCG** [comment] 2023-09-19 05:15
Same problem there.

**Comment by Arjentix** [comment] 2023-09-19 10:59
Same here.

I hope @sienori  will not abandon it

**Comment by SilentPrayeCG** [comment] 2023-09-21 02:54
I also noticed that it seems to be working fine again. Maybe it was something with google translate service itself?

**Comment by llleeexxxoooppp** [comment] 2023-09-21 06:32
> It seems to be working for me now. I didn't do anything. Someone please tell me if they still have this problem. Otherwise, I'll close issue.

Yes it is now, after updating Firefox to 118

**Comment by OPerepadia** [comment] 2023-09-21 07:53
I'm still using Firefox 117.0.1, but it seems to be working again for me too

**Comment by OnurDnz** [comment] 2023-09-21 08:32
In Firefox 117.0.1, working like a charm

**Comment by sienori** [comment] 2023-09-21 12:36
This seems to have been fixed by a change in Google's API.

**Closed** 2023-09-21 12:40 UTC
Labels: bug, fixed

**Comment by ttrasn** [comment] 2023-09-21 13:21
Hi @sienori, seems the plugin didn't update. could you please check it?

https://addons.mozilla.org/en-US/firefox/addon/simple-translate/
