### ISSUE TITLE
Latest update causes FF 65 (linux 64bit) to hangs

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/simple-translate#130] opened 2019-02-23 18:46 UTC
This is a empirical observation, today simple-translate updated, and after that FF became unusable with CPU constantly at 25%.

When simple-translate is disabled everything is fine (and to disable it, it was a struggle as FF is not responding).

I looked at the changelog but I am not a coder so I don't know what was changed that causes the issues, but please revert it as it makes FF unusable. I have to disable this very useful addon until something is done :(

**Comment by sienori** [comment] 2019-02-23 19:26
Please restart the browser and close it if a lot of tabs are opened.

**Comment by WPFilmmaker** [comment] 2019-02-23 19:28
By "close it" you mean disable the addon? That's what I did. And yes I have lot of open tabs open (I also use tab manager). Any way I can provide more information to you?

**Comment by sienori** [comment] 2019-02-23 19:32
"Close it" means to close the tab.

I found a problem in the code. I will fix it within a few days.
Sorry for the inconvenience.

**Comment by sienori** [comment] 2019-02-23 21:10
I fixed the problem and released version 2.0.1.

**Comment by WPFilmmaker** [comment] 2019-02-23 21:22
thanks for the quick response!

**Comment by WPFilmmaker** [comment] 2019-02-24 00:15
@sienori I updated and while things seem to be working a bit better (before it was unusable now it is slow) the moment I enable simple-translate CPU goes up to 30% and fans run.. :/

Is it related to the debug mode?

**Comment by sienori** [comment] 2019-03-02 08:17
The cause is that the size of the content script has been increased by using the library called React.
I will work on reducing the script size.

**Comment by WPFilmmaker** [comment] 2019-03-02 13:19
@sienori thank you very much for your hard work!

**Closed** 2019-07-29 08:32 UTC
Labels: bug, fixed
